esphome:
  name: tcl-ac-controller
  friendly_name: "TCL Air Conditioner"

esp32:
  board: esp32dev
  framework:
    type: arduino

# 💡 تحديد المسار المباشر للمكون داخل المستودع
external_components:
  - source:
      type: git
      url: https://github.com/lNikazzzl/tcl_ac_esphome
      path: custom_components

wifi:
  ssid: "TOTOLINK ND300"
  password: "A777763945A"

  ap:
    ssid: "Tcl-Ac-Fallback"
    password: "password123"

captive_portal:

api:
  password: ""

ota:
  password: ""

logger:

uart:
  - id: uart_ac
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600
    parity: EVEN
    stop_bits: 1

climate:
  - platform: tcl_ac
    name: "TCL AC"
    uart_id: uart_ac
    supports_cool: true
    supports_heat: true
    supports_fan_only: true
    supports_dry: true
    supports_auto: true
    
